# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 308)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 60, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.combo_box_method = QtWidgets.QComboBox(self.centralwidget)
        self.combo_box_method.setGeometry(QtCore.QRect(200, 30, 261, 22))
        self.combo_box_method.setObjectName("combo_box_method")
        self.combo_box_method.addItem("")
        self.combo_box_method.addItem("")
        self.combo_box_method.addItem("")
        self.spin_box_experts = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_box_experts.setEnabled(False)
        self.spin_box_experts.setGeometry(QtCore.QRect(230, 60, 42, 22))
        self.spin_box_experts.setMinimum(2)
        self.spin_box_experts.setMaximum(10)
        self.spin_box_experts.setObjectName("spin_box_experts")
        self.spin_box_terms = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_box_terms.setEnabled(False)
        self.spin_box_terms.setGeometry(QtCore.QRect(230, 100, 42, 22))
        self.spin_box_terms.setMinimum(2)
        self.spin_box_terms.setMaximum(5)
        self.spin_box_terms.setObjectName("spin_box_terms")
        self.button_terms = QtWidgets.QPushButton(self.centralwidget)
        self.button_terms.setEnabled(False)
        self.button_terms.setGeometry(QtCore.QRect(180, 180, 231, 23))
        self.button_terms.setObjectName("button_terms")
        self.button_matrix = QtWidgets.QPushButton(self.centralwidget)
        self.button_matrix.setEnabled(False)
        self.button_matrix.setGeometry(QtCore.QRect(180, 220, 231, 23))
        self.button_matrix.setObjectName("button_matrix")
        self.button_next = QtWidgets.QPushButton(self.centralwidget)
        self.button_next.setEnabled(False)
        self.button_next.setGeometry(QtCore.QRect(180, 260, 231, 23))
        self.button_next.setObjectName("button_next")
        self.spin_box_elements = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_box_elements.setEnabled(False)
        self.spin_box_elements.setGeometry(QtCore.QRect(230, 140, 42, 22))
        self.spin_box_elements.setMinimum(2)
        self.spin_box_elements.setMaximum(10)
        self.spin_box_elements.setObjectName("spin_box_terms_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 140, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.combo_box_method.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Построение функции принадлежности"))
        self.label.setText(_translate("MainWindow", "Метод построения:"))
        self.label_2.setText(_translate("MainWindow", "Количество экспертов:"))
        self.label_3.setText(_translate("MainWindow", "Количество термов:"))
        self.combo_box_method.setItemText(0, _translate("MainWindow", "Статистическая обработка мнений экспертов"))
        self.combo_box_method.setItemText(1, _translate("MainWindow", "Парные сравнения"))
        self.combo_box_method.setItemText(2, _translate("MainWindow", "Выберите метод"))
        self.button_terms.setText(_translate("MainWindow", "Ввод значений термов"))
        self.button_matrix.setText(_translate("MainWindow", "Ввод матрицы исходных данных"))
        self.button_next.setText(_translate("MainWindow", "Построить функцию принадлежности"))
        self.label_4.setText(_translate("MainWindow", "Количество элементов:"))
